/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Tomek Suchodolski (https://sketchfab.com/XID3)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/headphone-retro-5d54d65c9eb942ec83c86c9ceae27faa
Title: beats
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Headphones(props) {

      const { nodes, materials } = useGLTF("/assets/models/beats.glb");
      const group = useRef()

      return (
          <group {...props} dispose={null} ref={group}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.B_logo.geometry}
                    material={materials["b logo.001"]}
                    position={[0, 0.028, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Clipping_Part2.geometry}
                    material={materials["Material.011"]}
                    position={[0, 0.105, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Clipping_Parts.geometry}
                    material={materials["Material.011"]}
                    position={[0, 0.107, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Emission.geometry}
                    material={materials["emis.001"]}
                    position={[0, 0.027, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Headset.geometry}
                    material={materials["Material.007"]}
                    position={[0, 0.07, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Headset001.geometry}
                    material={materials["ear part.001"]}
                    position={[0, 0.042, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Headset002.geometry}
                    material={materials["Material.007"]}
                    position={[0, 0.033, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Left_Indicator.geometry}
                    material={nodes.Left_Indicator.material}
                    position={[0.076, 0.093, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Right_Indicator.geometry}
                    material={nodes.Right_Indicator.material}
                    position={[-0.076, 0.094, 0]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Wireless_text.geometry}
                    material={materials["logo2.001"]}
                    position={[0.081, 0.108, -0.003]}
                />
          </group>
      );
}

useGLTF.preload("/assets/models/beats.glb");